# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensitive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
