# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensitive', '0002_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
